<html>
<head><title>~wjc</title>
<link rel="stylesheet" type="text/css" href="../wjc.css">
<link href="http://fonts.googleapis.com/css?family=Playball" rel="stylesheet" type="text/css">
<script src='http://tilde.club/~gschueler/js/tildelink.js'></script>
</head>
<body>

<h1>Bill is in <a href="http://tilde.club">~&#x2663;</a></h1>
<!-- happy to be part of this super dumb thing from ftrain -->
<div id="menu">
<ul>
	<li><a href="/~wjc/index.html">home</a></li>
	<li><a href="http://twitter.com/wjcstp">&#x1F426; twitter</a></li>
	<li><a href="http://mlkshk.com/user/wjcstp">&#x1F4F7; mlkshk</a></li>
	<li><a href="http://flickr.com/photos/42462159@N00/sets">&#x1F4F7; flickr</a></li>
</ul>
</div>
