

<p>this is fun, thanks, <a href="http://tilde.club/~ford">paul</a>!</p>
<h3><a href="clublinks.html">Some cool tilde user sites</a></h3>

<!-- Begin Tilde.Club Ring Fragment-->
<center>
<font size="2">
</font></p><center><font size="2">
<center>
<br><img src="http://tilde.club/~harper/webring.png"  border="0" usemap="#notepad.map"><br>
</center>
<br>
Click for the [
<a href="http://tilde.club/~harper/link.html?action=random" target="_top">Random page</a> ]
<br>
Want to join the ring? Click here for
<a href="http://tilde.club/~harper/link.html?action=info" target="_top">info</a>.
<br></font></center>
<map name="notepad.map">
<area shape="rect" coords="0, 0, 60, 70" target="_top" href="http://tilde.club/~harper/link.html?action=join">
<area shape="rect" coords="130, 0, 417, 75" target="_top" href="http://tilde.club/~harper/link.html?action=random">
<area shape="rect" coords="465, 0, 549, 75" target="_top" href="http://tilde.club/~harper/link.html?action=join">
</map>
</center>
<!-- End Webring Fragment-->

<!-- Start of SimpleHitCounter Code -->
<div align="center"><a href="http://www.simplehitcounter.com" target="_blank"><img src="http://simplehitcounter.com/hit.php?uid=1794199&f=16777215&b=0" border="0" height="18" width="83" alt="web counter"></a><br><a href="http://www.simplehitcounter.com" target="_blank" style="text-decoration:none;">web counter</a></div>
<!-- End of SimpleHitCounter Code -->


</body>
</html>
